on:
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  check_releases:
    runs-on: ubuntu-latest
    outputs:
      libraries: ${{ steps.check-releases.outputs.libraries }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - id: check-releases
        run: echo "::set-output name=libraries::$(echo [ \"lib1\", \"lib2\" ])"
  test_releases:
    runs-on: ubuntu-latest
    needs: check_releases
    strategy:
      matrix: ${{ fromJson(needs.check_releases.outputs.libraries) }}
    steps:
      - run: echo "${{ matrix }}"
